---

- name: Environment file
  when:
    - semaphoreui_webproxy_env_enable | bool
    - semaphoreui_webproxy_env_file | length > 0
    - semaphoreui_webproxy_env_content | length > 0
  block:
    - name: Set custom env file for semaphoreui
      ansible.builtin.copy:
        content: "{{ semaphoreui_webproxy_env_content }}"
        dest: "{{ semaphoreui_webproxy_env_file }}"
        mode: '0640'
        owner: root
        group: "{{ semaphoreui_user }}"

# if issue, check /var/log/audit/audit.log
- name: Add systemd unit
  ansible.builtin.template:
    src: systemd-semaphoreui.service.j2
    dest: /etc/systemd/system/semaphoreui.service
    mode: '0644'
    owner: root
  notify:
    - Reload systemd
    - Restart semaphoreui
