---

# if issue, check /var/log/audit/audit.log
- name: Add systemd unit
  ansible.builtin.template:
    src: systemd-semaphoreui.service.j2
    dest: /etc/systemd/system/semaphoreui.service
    mode: '0644'
    owner: root
  notify:
    - Reload systemd
    - Restart semaphoreui
