---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  when:
    - not is_container | bool

- name: Restart semaphoreui
  ansible.builtin.service:
    name: semaphoreui
    state: restarted
  become: yes
  become_user: root
  when:
    - not is_container | bool
