---
name: default-bare

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every Tuesday 02:00
    - cron: '0 2 * * 2'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-${{ matrix.version }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - distribution: ubuntu
            version: '24.04'
            suite: default
            experimental: true
          - distribution: ubuntu
            version: '22.04'
            suite: default
            experimental: false
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.semaphoreui
      ANSIBLE_SUITE: ${{ matrix.suite }}

    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ env.ANSIBLE_ROLE }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
          echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
          ansible --version
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          set -x
          pwd
          env
          find . -ls
      - name: Before script - mysql
        run: |
          set -x
          ls -l /etc/mysql/
          sudo cat /etc/mysql/debian.cnf || true
          sudo cat /etc/mysql/my.cnf || true
          # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#mysql
          sudo systemctl start mysql.service
          mysql -u root -p root -e 'show databases' || true
          sudo env DEBIAN_FRONTEND=noninteractive apt-get purge mysql-server mysql-common -y
        if: ${{ always() }}
        continue-on-error: true
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS} | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: verify
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -vvv molecule/$ANSIBLE_SUITE/verify.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: On failure
        run: |
          systemctl -l --no-pager status
          systemctl -l --no-pager --failed
          ls -l /usr/bin/ | egrep '(python|pip|ansible)'
          pip freeze
          pip3 freeze
          ip addr
          cat /etc/resolv.conf
          host www.google.com
          ping -c 1 www.google.com || true
          ping -c 1 8.8.8.8 || true
          ps axuw
          netstat -anp
        if: ${{ failure() }}
        continue-on-error: true
      - name: After script - ansible setup
        run: |
          ansible -i inventory --connection=local -m setup localhost
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - systemd
        run: |
          systemctl -l --no-pager status semaphoreui || true
          systemd-analyze --no-pager security || true
          systemd-analyze --no-pager security semaphoreui || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - files
        run: |
          set -x
          sudo ls -la /var/_semaphoreui/
          sudo sqlite3 /var/_semaphoreui/env-semaphoreui/lib/python3.12/site-packages/open_webui/data/webui.db -batch -safe '.tables'
          sudo cat /etc/default/semaphoreui
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - mysql
        run: |
          set -x
          ls -l /etc/mysql/
          sudo cat /etc/mysql/debian.cnf || true
          sudo cat /etc/mysql/my.cnf || true
          ls -l /var/lib/mysql/
          sudo ls -l ~/.my.cnf /root/.my.cnf || true
          mysql -e 'show tables' semaphoredb || true
          mysql -e 'show schemas' semaphoredb || true
          mysql -u root -e 'show tables' semaphoredb || true
          mysql -u root -e 'show schemas' semaphoredb || true
          mysql -u root -p root -e 'show tables' semaphoredb || true
          mysql -u root -p root -e 'show schemas' semaphoredb || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - mysql logs
        run: |
          set -x
          ls -l /var/log/mysql/*.log || true
          sudo tail -n50 /var/log/mysql/*.log || true
          sudo tail -n50 /var/lib/mysql/*.log || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - curl
        run: |
          curl -vL http://localhost:8080 || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl
        run: |
          set -x
          sudo journalctl -u semaphoreui -l --no-pager
          sudo journalctl -u mysql -l --no-pager
        if: ${{ always() }}
        continue-on-error: true
